### ISSUE TITLE
Error: Cannot find module '../lightningcss.win32-x64-msvc.node'

### ISSUE THREAD

**Issue by cayquesilva** [rocketseat-education/nlw-unite-react-native#1]
Olá estou usando o windows 11, com tudo instalado conforme a trilha de react-native, já instalei o modulo em questão e não tenho sucesso de forma alguma.

segue erro:
![imagem_2024-04-06_203406487](https://github.com/rocketseat-education/nlw-unite-react-native/assets/31603331/bdfc9a3c-7f05-4858-a529-a29d9587f1e5)

rapidamente ao rodar o npm i, vi a instalação do lightningcss-arm, não se se esse seria o erro, sou iniciante...

**Comment by cayquesilva** [comment]
O erro persiste tanto fazendo tudo do zero, conforme trilha formativa, como também clonando a aula 1 aqui do repositório...

**Comment by cayquesilva** [comment]
` let parts = [process.platform, process.arch];
if (process.platform === 'linux') {
  const { MUSL, family } = require('detect-libc');
  if (family === MUSL) {
    parts.push('musl');
  } else if (process.arch === 'arm') {
    parts.push('gnueabihf');
  } else {
    parts.push('gnu');
  }
} else if (process.platform === 'win32') {
  parts.push('msvc');
}

if (process.env.CSS_TRANSFORMER_WASM) {
  module.exports = require(`../pkg`);
} else {
  try {
    module.exports = require(`./lightningcss-${parts.join('-')}`);
  } catch (err) {
    module.exports = require(`../lightningcss.${parts.join('-')}.node`);
  }
}

module.exports.browserslistToTargets = require('./browserslistToTargets');
module.exports.composeVisitors = require('./composeVisitors');
module.exports.Features = require('./flags').Features;
 `

Aqui está onde o erro está sendo gerado

**Comment by Mauricio2025** [comment]
Olá Boa noite . 

- Primeiro passo ao puxar a pasta onde contem os arquivos antes mesmo de executar o npm i, você entra no codigo ver se esta amostrando algum erro lá se não tiver se vai fazer o seguinte vai instalar todas as dependencias uma por uma do arquivo package.json é depois de instalar tudo ai você dar o npm i e ser mesmo assim não funcionar vai reiniciar seu pc e dar o npx expo --clear.

**Comment by cayquesilva** [comment]
Olá, consegui resolver reinstalando meu Node. Percebi que ao instalar no windows, caso marcasse a opção de instalar os pacotes adicionais, sempre retornava esse erro...

Grato pela ajuda @Mauricio2025
